# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yarvin
tagline:             ''
description:         ''
url:                 http://yarvin.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Alvin Morris
  url:               https://twitter.com/skriptmonkey
  email:             

# Custom vars
version:             1.0.0
